In [1]:
import numpy as np

In [2]:
np.logspace(-4,1,9)

array([1.00000000e-04, 4.21696503e-04, 1.77827941e-03, 7.49894209e-03,
       3.16227766e-02, 1.33352143e-01, 5.62341325e-01, 2.37137371e+00,
       1.00000000e+01])

In [4]:
np.log10([1.77827941e-03,7.498E-3,2.37])

array([-2.75      , -2.12505456,  0.37474835])

In [ ]:
Belva = [-2.25,.5]

In [5]:
np.log10([5.62341325e-01,1.77827941e-03])

array([-0.25, -2.75])

In [6]:
Cobi = [-2.75,0]

In [7]:
np.log10(.004)

-2.3979400086720375